### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [penguin-astronaut/penguin-astronaut.github.io#1]
Отличная верстка!

1. 
![image](https://user-images.githubusercontent.com/57518708/74806729-d7414480-52f7-11ea-87d9-c11f1c83feb1.png)
Первая кнопка - это то, как выглядит вторая на `:hover`
![image](https://user-images.githubusercontent.com/57518708/74806951-559de680-52f8-11ea-97e7-afa07f6f9678.png)
Тут то же самое

2. Стилизация чекбокса http://dimox.name/custom-checkboxes-and-radio-buttons-using-css-only/

**Comment by penguin-astronaut** [comment]
Исправлено!
